# Generated by Django 2.0.6 on 2018-06-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('permalink', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=400)),
                ('permalink_url', models.CharField(max_length=400)),
                ('avatar_url', models.CharField(max_length=400)),
            ],
        ),
    ]
