# Generated by Django 2.0.6 on 2018-06-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savesounds', '0002_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='expires_in',
            new_name='expires',
        ),
    ]
