# Generated by Django 2.0.6 on 2018-06-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savesounds', '0003_auto_20180615_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='scope',
        ),
    ]
