# Generated by Django 2.0.6 on 2018-06-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savesounds', '0004_auto_20180615_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
