# Generated by Django 2.0.6 on 2018-06-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savesounds', '0007_accesstoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
