# Generated by Django 2.0.6 on 2018-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savesounds', '0008_user_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
